version: '3.6'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:9.6-alpine'
    restart: always
    volumes:
      - '.docker/postgresql:/var/lib/postgresql/data'
  web:
    build: .
    command: iex -S mix phx.server
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    tty: true
    ports:
      - '4000:4000'
    volumes:
      - /home/app/deps
      - /home/app/_build
      - /home/app/.mix
      - .:/home/app
volumes:
  pgdata: